title: "[TODO] "
labels: ["오늘 할 일"]
body:
  - type: markdown
    attributes:
      value: |
        오늘 할 일을 작성합니다.
  - type: textarea
    id: todos
    attributes:
      label: 오늘 주요 할 일
      description: "오늘 할 일은 무엇인가요?"
      placeholder: "예시) 1. TIL 작성하기\n2. 이슈 작성하기\n3. PR 보내기"
      value: |
        **권재은**
        1. 
        2. 
        3. 
        4. 
        **이우창**
        1. 
        2. 
        3. 
        4. 
        **인성준**
        1. 
        2. 
        3. 
        4. 
        **지윤식**
        1. 
        2. 
        3. 
        4. 
        **박범진**
        1. 
        2. 
        3. 
        4. 
        **정휘상**
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
