title: "[TODO] "
labels: ["오늘 할 일"]
body:
  - type: markdown
    attributes:
      value: |
        오늘 할 일을 작성합니다.
  - type: textarea
    id: todos
    attributes:
      label: 오늘 주요 할 일
      description: "오늘 할 일은 무엇인가요?"
      placeholder: "예시) 1. TIL 작성하기\n2. 이슈 작성하기\n3. PR 보내기"
      render: bash
    validations:
      required: true
  - type: input
    id: username
    attributes:
      label: GitHub 사용자명
      default: @{{ github.actor }}
  - type: input
    id: timestamp
    attributes:
      label: 작성 시간
      default: {{ date }
